### Options

```{r}
# Create page-specific logger (logging system already loaded globally)
page_logger <- create_module_logger("PAGE12-PARTICIPANT-SUMMARY")
page_logger("DEBUG", "Initializing participant summary page options")

selectizeInput("participantSummary", "participant",
  choices = participants, selected = participants[1], multiple = TRUE
)
actionButton("addAllParticipants", "Add All Participants")
```

Column
--------------------------------------------

### Participant pool
Get summary of participant demographics etc.

(This was previously a place in which we could generate PDF reports of each participant (see old commits), but this feature required a lot of extra work to keep it running so it was removed.)
```{r}
tableOutput("participant_details_table")
```


```{r, context="server"}
# Use the page logger already created in the options section

observeEvent(input$addAllParticipants, {
  page_logger("DEBUG", "Adding all participants to summary")
  updateSelectizeInput(session, "participantSummary", selected = participants)
})

### Participant pool summary
output$participant_details_table <- renderTable(
  {
    page_logger("DEBUG", "Rendering participant details table for", length(input$participantSummary), "participants")
    participants <- input$participantSummary # filterParticipants
    participant_details <- calculate_participant_details(participants)

    return(participant_details)
  },
  rownames = TRUE,
  options = list(pageLength = 100, scrollY = "500px")
)
```