---
title: "VFD for gait variability"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll # scroll # fill
runtime: shinyrmd
---

```{r setup, include=FALSE}
rmarkdown::shiny_prerendered_clean("workspace/index.Rmd") # we need to clear else it doesnt start the interface for whatever reason. 

source('source/setup.R')
source('source/data_loading.R', local = FALSE)
source('source/pre_processing.R', local = FALSE)

source('source/find_foot_events.R', local = FALSE)

## Get Results
source('source/calc_all_gait_params.R', local = FALSE)
source('source/get_questionnaire_results.R', local = FALSE)

# File paths
resultsFolder <- "results"
agpFile <- file.path(resultsFolder, "allGaitParams.rds")
aqrFile <- file.path(resultsFolder, "allQResults.rds")

# Load or calculate the data
allQResults <- load_or_calculate(aqrFile, get_all_questionnaire_results)
allGaitParams <- load_or_calculate(agpFile, calc_all_gait_params)

dataTypes         <- setdiff(getTypes(allGaitParams), categories)

## Summary tables
source('source/summaryparams.R', local = FALSE)
mu <- get_full_mu_sliced(allGaitParams, allQResults, categories, 180, avg_feet=FALSE, add_diff = TRUE)
muDataTypes <- setdiff(getTypes(mu), categories)
muVars <- colnames(mu)
## Plotting code
source('source/plotting.R', local = FALSE)
```


Sidebar {.sidebar}
=====================================
```{r, child='pages/sidebar_dynamicDataFiltering.Rmd'}
```

```{r, context="server", local=FALSE}
source('source/get_filtered_data.R', local = TRUE)
```


```{r, context="server", local=FALSE}
session$allowReconnect(TRUE)

refresh_trigger <- reactiveVal(0) # used for refreshing filteredGaitParams after outlier update

#Custom function used to render SVG's instead of png's
renderSVG <- function(expr) {
  renderImage({
    # Dynamically get width and height from input
    dpi <- 96
    width_value <- input$plotwidth / dpi
    height_value <- input$plotheight / dpi

    file <- htmltools::capturePlot(
      expr(), tempfile(fileext = ".svg"),
      grDevices::svg,
      width = width_value, height = height_value
    )
    list(src = file, deleteFile = TRUE)
  }, deleteFile = TRUE)
}
```

Data Dictionary.md {data-orientation=columns}
=====================================
```{r, echo=FALSE}
shiny::includeMarkdown('data_dictionary.md')
```

Feet trajectories {data-orientation=columns}
=====================================
```{r, child='pages/page1_feetTrajectories.Rmd'}
```


Removed Steps
=====================================
```{r, child='pages/page2_removedSteps.Rmd'}
```


Raw tracker data {data-orientation=columns}
=====================================
```{r, child='pages/page3_rawTrackerData.Rmd'}
```


Histograms 
=====================================
```{r, child='pages/page5_histograms.Rmd'}
```

Scatterplots
=====================================
```{r, child='pages/page6_scatterplots.Rmd'}
```

